# Generated by Django 4.1 on 2022-08-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='None', max_length=200, null=True)),
                ('designation', models.CharField(default='None', max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='none', max_length=200, null=True)),
                ('type', models.CharField(choices=[('Device', 'device'), ('Package', 'package'), ('Other', 'other')], default='other', max_length=200, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('description', models.CharField(default='none', max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
